### ISSUE TITLE
Attention implementation possible bug

### ISSUE THREAD

**Issue by shenxiangzhuang** [Khaliladib11/Transformer-from-scratch#1]
https://github.com/Khaliladib11/Transformer-from-scratch/blob/ee1b17dded5b93e4ba1522425d022179c1624503/src/attention.py#L36-L42

Is there any problem here? I think it should be the following code:
```python
 key = key.reshape(batch_size, k_len, self.heads, self.head) 
 query = query.reshape(batch_size, q_len, self.heads, self.head)  # CHANGE HERE to query.reshape
 value = value.reshape(batch_size, v_len, self.heads, self.head)  # CHANGE HERE to value.reshape
  
 key = self.key(key)  # (32x10x8x64) 
 query = self.query(query)  # (32x10x8x64)    # CHANGE HERE to self.query
 value = self.value(value)  # (32x10x8x64)  # CHANGE HERE to self.value
```

**Comment by AbhinavJangra29** [comment]
this code is pretty confusing to understand lacks proper documentation

**Comment by Khaliladib11** [comment]
Thank guys for the feedback @AbhinavJangra29 and @shenxiangzhuang.

@AbhinavJangra29 did a PR and fixed the typo, also I will try to add more documentation later
